### ISSUE TITLE
Раскрытие активного элемента левого меню при работе с средним окном

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#102]
Открываю программу. Открываю в среднем окне "Подключение к БД". В левом меню подсвечивается в списке пункт "Подключение к БД".
Ожидаемое поведение: в левом меню этот пункт не только подсвечен, но и раскрыт. 
Кажется такое же я видел в проводнике Windows при включёном режиме дерева.
![image](https://cloud.githubusercontent.com/assets/4630662/5471192/b3d3c9bc-8603-11e4-8c04-1f93b246c187.png)

**Comment by BishopGIS** [comment]
Нет такого. Этот элемент раскроется когда ты перейдешь ниже по дереву, например в папку "Новая папка". Это происходит т.к. в дереве надо показывать выделенный элемент. Насчет такого "нестандартного" раскрытия - нужны еще мнения. Из минусов вижу, что при навигации в окне содержимого, будет много раскрытых элементов в дереве, что будет забивать это самое дерево  и потом придется много скролить.

**Comment by BishopGIS** [comment]
Проверил в проводике Windows и ArCatalog - у меня сделано также как и у них. Поведение стандартное. Закрываю, т.к. нестанедартное раскрытие может сбивать с толку.
