### ISSUE TITLE
Не загружаются растры в NGW

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#103]
При попытке загрузки 4-канального tiff
![image](https://cloud.githubusercontent.com/assets/4630662/5502764/a4d41a52-877f-11e4-9a13-b73e1eeceec3.png)

Через веб-интерфейс они грузятся и показываются успешно.

**Comment by BishopGIS** [comment]
А какая версия? Последняя 0.6.4

**Comment by trolleway** [comment]
Пересобрал сегодня. Всё по-прежнему.

**Comment by BishopGIS** [comment]
Мне нужен пример растра хоть через google drive хоть еще как-то. Ты тестировал на Центрально-Черноземном?
И еще - я надеюсь ты слой создаешь через контекстное меню "Импорт", а не drag'n'drop-ом. Иначе должен создаваться набор файлов, которые инстанс не поддерживает, о чем должно быть соответствующее диалоговое окно.

**Comment by BishopGIS** [comment]
Проверил на переданном растре - все равно не воспроизводится:
http://176.9.38.120/krs/resource/122
Все работает как надо.
В группе ресурсов вызываем контекстное меню выбираем пункт импорт и в открывшемся диалоге выбираем файл M-37-013.tif. Далее задаем ему имя, не совпадающее с теми что есть в этой группе и более ничего не меняя нажимаем ОК.
Кто ни будь еще может проверить: вот сам файл для теста - http://demo.nextgis.ru/rekod/resource/782/file/M-37-013.tif (надо быть залогиненым)
Грузить можно в любой инстанс.

**Comment by trolleway** [comment]
Да, оказывается надо было пользоваться функцией "Импорт", а я делал drag-n-drop
