### ISSUE TITLE
ALTER DEFAULT PRIVILEGES IN SCHEMA

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#104]
Ожидаемое поведение: 
- создал в менеджере схему, 
- кинул в неё шейп-файл, 
- открыл в менеджере подключение к NGW,  
- открыл в нём подключение к БД, 
- перенёс таблицу в БД в слой данных
- открыл веб-интерфейс NGW, добавил к этому слою стиль, и положил его на веб-карту.

Менеджер при создании схемы БД не делает ALTER DEFAULT PRIVILEGES IN SCHEMA
Возможно что из-за этого возникают ошибки при попытке добавить таблицы из этой схемы в NGW.     Если ошибки из-за этого, то их очень сложно понять и отловить. Нужно или предлагать сделать  ALTER DEFAULT PRIVILEGES IN SCHEMA, или выдавать предупреждение, что нужно это сделать вручную, или проверять схему на отсутствие прав.

**Comment by BishopGIS** [comment]
Дублирование #21
