### ISSUE TITLE
Ctrl+C, Ctrl+V not working

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgismanager#108]
neither keyboards, nor right-click menus

tried on connection

If they are not supposed to work, may be remove them from menu at least?

**Comment by BishopGIS** [comment]
What is the OS and connection type (web, db, etc.)?

**Comment by BishopGIS** [comment]
On Windows Ctrl+C, Ctrl+V works. For example I copy database connection and past it on disk D:

**Comment by BishopGIS** [comment]
On Linux everything works same as on Windows.

**Comment by simgislab** [comment]
Ubuntu Linux, trying to copy and paste connection (wconn)

**Comment by BishopGIS** [comment]
Works for me. Anybody can reproduce?

**Comment by drnextgis** [comment]
Cannot reproduce here (Linux Ubuntu).
