### ISSUE TITLE
Не отображает поле PK

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#110]
При подключении к PostgreSQL не отображает поле таблицы, содержащее первичный ключ.

**Comment by BishopGIS** [comment]
GDAL считает это поле как FID. Сделал его вывод в сетке

**Comment by drnextgis** [comment]
У меня как не отображалось, так и не отображается.

**Comment by BishopGIS** [comment]
Рядом со стрелочкой циферки это и есть значения поля PK. GDAL принял решение использовать это поле в качестве FID, поэтому в перечне полей оно отсутвует. Я его показываю вот таким образом. Обрати внимание: цифры не по порядку, т.к. значения пропущены (удалили или такой номер присвоили)
![2015-02-03 10 51 40](https://cloud.githubusercontent.com/assets/1708122/6016418/b5cdd096-ab92-11e4-9f1e-72ae0b35b683.png)

**Comment by drnextgis** [comment]
Теперь понятно, но это надо знать, иначе сложно догадаться. А в каком порядке отображаются записи?

**Comment by BishopGIS** [comment]
Порядок как GDAL выдает, но можно сортировать - можно сделать как ни будь через контекстное меню.
