### ISSUE TITLE
Connections aren't showed after saving

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgismanager#114]
Connections are created and saved ok, but don't show up in the tree. Permissions are ok, Ubuntu 14.04

> -rw-rw-r-- 1 sim sim  118 февр.  6 09:49 ngw.wconn
> -rw-rw-r-- 1 sim sim 1045 февр.  6 09:58 tms.wconn

**Comment by BishopGIS** [comment]
#wontfix
Not shown because gdal was compiled withot wfs wms and postgis

**Comment by simgislab** [comment]
see #122
