### ISSUE TITLE
Загрузка данных в NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#148]
Выделяю группу ресурсов, в контекстном меню выбираю `Импорт`, выбираю файл (MIF), открывается вот такое окно:
![2015-10-28 12 14 05](https://cloud.githubusercontent.com/assets/866124/10781023/54d028a2-7d65-11e5-90b9-1af69ea7ae3a.png)

Если нажать на красный крестик, то открывается окно:
![2015-10-28 12 14 29](https://cloud.githubusercontent.com/assets/866124/10781032/69be8cb8-7d65-11e5-9190-6f846cc6ce57.png)

Мне кажется тут что-то не так.

**Comment by BishopGIS** [comment]
Так и задумывалось. Диалог предназначен для массовой загрузки данных. Для каждого набора по панели. Если в какой-то панели невалидные данные или просто случайно попали данные которые не нужно грузить используется крестик что бы удалить этот набор.
Можно сделать закрытие диалога при удалении последнего набора (панели) из диалога. Но вот будет ли это понятно пользователю?

**Comment by drnextgis** [comment]
Понял, а почему красный знак слева? Почему поля с выходным именем и кодировкой не активны? Почему второе окно пустое?

UPD.: понял, никакого второго окна нет, это просто первое очищенное от записей.

**Comment by BishopGIS** [comment]
Надо навести курсор на красную иконку и там в тултипе будет описание, почему этот слой не может быть загружен. У иконки есть 3 состояния. Зеленое - нет проблем с загрузкой, желтое - есть какие-то проблемы (подробности в тултипе), красное - проблемы не позволяющие загрузить. Когда грузится по 30-50 файлов такой диалог вполне удобен. Для одного, конечно несколько нелогично.

**Comment by drnextgis** [comment]
Понял, пишет что система координат 'Noneearth' не поддерживается. А попробуй сделать Импорт - Выбрать любой слой, потом крестиком его удалить, закрыть окно, потом снова эту процедуру повторить - у меня стабильно вылетает.
