### ISSUE TITLE
Не загружается Shapefile в базу PostGIS, если в нём есть поле ogc_fid

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#15]
Если загружать в базу шейп, в котором уже есть поле ogc_fid, то появится ошибка "поле ogc_fid в базе данных уже есть", и он не загрузится. Надо, что бы в таком случае поле ogc_fid из шейпа не использовалось.

**Comment by BishopGIS** [comment]
Fixed in a99650c1d492f717be9ef2a85b8d3d99affc7405
