### ISSUE TITLE
В диалоге импорта нет поля с типом геометрии

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#151]
Выбираем 1 файл, а в диалоге появляется 3 элемента и не понятно какой из них к какому типу геометрии относится. Точнее вроде эта информация содержится в выходном имени, но мне кажется это удобней было бы выводить еще и отдельным readonly полем, чтобы не скроллить длинные названия слоёв (в данном примере так как слой невалидный так вообще не поскроллить)
![2015-11-01 04 41 51](https://cloud.githubusercontent.com/assets/866124/10866314/9b85526c-804a-11e5-9270-2b1b1fd2ab9c.png)

**Comment by BishopGIS** [comment]
Идея хорошая - подправлю.
