### ISSUE TITLE
Не удаляются настройки прокси

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#156]
Удаляю хост и порт, жму ОК, потом опять захожу в настройки - порт и хост на месте.

**Comment by drnextgis** [comment]
Спасибо, проблема решена. А можно сделать так, чтобы настройки прокси не удалялись при снятии галки? Чтобы можно было быстро его включать-выключать.

**Comment by BishopGIS** [comment]
А разве они удаляются? Этого не должно происходить.

**Comment by drnextgis** [comment]
Да, значения очищаются.
