### ISSUE TITLE
Как лучше поставить ngm на ubuntu 14.04

### ISSUE THREAD

**Issue by paleogis** [nextgis/nextgismanager#158]
Подскажите пожалуйста, как лучше установить и запустить  ngm на ubuntu 14.04, 
git clone уже сделал. Спасибо.

**Comment by simgislab** [comment]
https://github.com/nextgis/nextgismanager/wiki/Install-and-Update-in-Ubuntu

Не уверен за полноту.

**Comment by paleogis** [comment]
Спасибо, Максим:)
