### ISSUE TITLE
Если в слое разные типы геометрий, то точки должны рисоваться над полигонами

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#16]
Если отрыть таблицу PostGIS в которой лежит геометрия разных типов, то точечные объекты выводятся на экран под площадными, и их не видно.
![image](https://cloud.githubusercontent.com/assets/4630662/2613370/54bd1fb2-bbd5-11e3-93ea-e8071c8e9813.png)

Хочу, что бы снизу были площадные, над ними - линейные, над ними - точечные.

**Comment by BishopGIS** [comment]
Слой выводится в том порядке как и представлены данные. И это правильно. Такая же ситуация может быть если в слое есть перекрывающиеся полигоны. 
Единственное, что будет сделано в этом направлении - возможность настройки стиля отображения. Тогда у полигона можно будет отключить заливку или сделать ее полупрозрачной.
