### ISSUE TITLE
Переименовать кнопку "Информация" в "Идентификация"

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#18]
![image](https://cloud.githubusercontent.com/assets/4630662/2731360/5352838c-c62b-11e3-83fe-4fd5b975ded1.png)

Предлагаю переименовать кнопку "Информация" в "Идентификация", что бы названия инструмента и окна были одинаковыми.

**Comment by BishopGIS** [comment]
Fix in 89fe11782ca7474dbd0869fc2077587dffc9e017
