### ISSUE TITLE
Не отображается иконка приложения в панели запуска Unity

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgismanager#23]
Ubuntu 12.04, стандартный рабочий стол Unity.

Не отображается иконка приложения в панели запуска после загрузки приложения. Причем, если не отображать сплэш, или если сплэш исчезнет раньше чем стартанет главный фрейм (или время отображения сплэша маленькое, или если срезу кликнуть по нему), то иконка отображается. 

Попробовал написать helloworld простой со спэшем - то же самое, а попробовал сплэшу добавить иконку - то helloworld заработал, а вот в ngm так не получилось..

**Comment by BishopGIS** [comment]
Fix in 443b61c8e148b89a684eb9f349c11685da69d1f5
