### ISSUE TITLE
Не работает команда "Присоединить папку" (Connect folder) из главного меню приложения.

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgismanager#24]
Ubuntu 12.04

При попытке выполнить команду "Присоединить папку" (Connect folder) из главного меню (практический всегда, бывает что отробатывает нормально) приложение зависает. Получем сообщение в логе: ../src/gtk/clipbrd.cpp(598): assert "!m_open" failed in Open(): clipboard already open. Приложение зависает вот так:
![screenshot from 2014-04-29 12 59 45](https://cloud.githubusercontent.com/assets/5332345/2827032/2661f3ee-cf7c-11e3-865c-7de378fd2a91.png)

**Comment by alisovenko** [comment]
Так-же часто к зависанию приводит попытка открыть окно View\Toolbars\Customize... Зависение сопровождается ассертом ../src/gtk/clipbrd.cpp(598): assert "!m_open" failed in Open(): clipboard already open
![screenshot from 2014-04-30 14 34 07](https://cloud.githubusercontent.com/assets/5332345/2840333/4f3b61ba-d053-11e3-92b8-0035e6f03f79.png)

**Comment by alisovenko** [comment]
Насколько я понял проблема в следующем:
В момент обработки события wxUpdateUIEvent в методе wxGISApplication::OnCommandUI может поступить событие wxCommandEvent (метод  wxGISApplication::OnCommand). Обработка события wxCommandEvent начинается после того, как при обработке события wxUpdateUIEvent открылся буффер обмена (wxGxTreeView::CanPaste()). А при обработке события wxCommandEvent повторно начинается обрабокта wxUpdateUIEvent с попыткой открытия буффера обмена (wxGxTreeView::CanPaste()). Нужно дождаться завершения обработки события wxUpdateUIEvent перед началом выполнения обработки wxCommandEvent.

**Comment by BishopGIS** [comment]
Присоединение работает на текущей версии, а вот отключение - приводит к падению. 
Пока не буду закрывать этот тике, так как активности взаимосвязанные.
