### ISSUE TITLE
Окно Tools\Options часто приводит к зависанию приложения

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgismanager#25]
Ubuntu 12.04

При попытке открыть окно настроек приложения Tools\Options (диалог wxPropertySheetDialog) приложение часто зависает оставляя открытым окно настроек без содержания.

Воспроизводится часто, иногда не воспроизводится - последовательность действий, приводящую к 100%-му зависанию, выявить не удалось.

![screenshot from 2014-04-30 14 30 36](https://cloud.githubusercontent.com/assets/5332345/2840271/8175153c-d052-11e3-93d5-40853da588ec.png)

**Comment by BishopGIS** [comment]
Fix in 1ff9bfe5d309d2311886f774ae152e776a290e66
