### ISSUE TITLE
Добавить пункт "Отключится от базы данных" в контекстное меню панели дерева

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#29]
![image](https://cloud.githubusercontent.com/assets/4630662/3356218/9f18b784-fabd-11e3-8e91-ab831d1a955f.png)

**Comment by BishopGIS** [comment]
А зачем он нужен?

**Comment by trolleway** [comment]
Вместо этого будет автоматическое переподключение к базе при изменении параметров подключения.
