### ISSUE TITLE
Автоматическое обновление списка файлов в папке.

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#33]
Подключаюсь к папке в файловой системе.
Другая программа кидает в неё ещё один файл.
В менеджере его не видно - нужно давать комманду "Обновить", а в разных файловых менеджерах в этом случае список файлов обновляется автоматически.

Можно сделать эту функцию отключаемой на всякий случай.

**Comment by BishopGIS** [comment]
Вообще он так и делает. Поэтому необходима более подробная инфомрация об этом баге. Единсвенное чего пока нет - это поддержки сетевых папок.

**Comment by BishopGIS** [comment]
Чего-то фидбэка не получил, считаю что не воспроизводится.
