### ISSUE TITLE
Do not show triangle if the container is empty or try to connect if triangle is clicked

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgismanager#38]
In this situation I believe you either shouldn't show the triange or show it and automatically start the connection if the triangle is clicked.

![](http://m-d.me/img/ss/2014-09-19-18-30-21.png)

**Comment by BishopGIS** [comment]
The logic is so: every container (folder, connection, db schema, KML files, etc.) potentially can have children, but in fact it can be no children. Getting a children from each container is heavy process. A children requested if the user open container. If there are no children triangle (or plus in Win) disappeared. To not lock the UI usually I add pending element.
In this case I think we can remove triangle for elements with connection properties, but disconnected yet - DB, Web services, etc. - the elements which linked with some remote services.

**Comment by simgislab** [comment]
yes, removing for disconnected sounds good! interface will get cleaner for sure
