### ISSUE TITLE
Добавить возможность создания папок в локальной файловой системе

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#4]
Юзкейс: на сервере PostGIS изменилась версия данных. Хочу скачать себе таблицу как Shape, и положить её в отдельную папочку.

**Comment by BishopGIS** [comment]
Решили переименовать "новый" на "создать"

**Comment by BishopGIS** [comment]
Fix in e6d081f80a8d698fb8a6d320c5a805c356d3e043
