### ISSUE TITLE
Падает, если нажать кнопку OK

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#46]
- Дважды кликаем на каком-нибудь файле в дереве
- В открывшемся окне свойств файла нажимаем OK
- NGM вываливается у меня в 100% случаев

**Comment by BishopGIS** [comment]
У меня не воспроизводится. Кто ни будь еще может подтвердить?

**Comment by drnextgis** [comment]
Если нажать правой кнопкой и выбрать `Properties`, а потом `OK`, то ничего не падает, а если вот так двойным кликом - то всегда.

**Comment by simgislab** [comment]
точно вываливается) щелкать нужно именно в дереве (слева), а не справа

> ./opt/update.sh: строка 6: 23539 Ошибка сегментирования                   (подготовлен дамп ядра) wxgiscat

**Comment by drnextgis** [comment]
Подтверждаю, починилось.
