### ISSUE TITLE
Delete 'new TMS connection.wconn' failed

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#47]
Создаю новое TMS-соединение, но не выбираю никаких пресетов, после этого его невозможно удалить. Если выбрать пресет, то удаляется.

**Comment by BishopGIS** [comment]
У меня не воспроизводится. Там скорее другой баг - это папка сама не обновляется при создании и удалении подключений.

**Comment by drnextgis** [comment]
Обновился сегодня - ошибка исчезла, видимо в https://github.com/nextgis/nextgismanager/commit/fb071813915b29acb2e035d145eba9c6d7e9a9c1 починилось.
