### ISSUE TITLE
NGW connection не работает с https

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#48]

**Comment by BishopGIS** [comment]
Как проверить?

**Comment by drnextgis** [comment]
`https://192.168.250.101:443`

**Comment by BishopGIS** [comment]
C https работает - там проблема с самоподписанным сертификатом: CURLE_PEER_FAILED_VERIFICATION
Я в настройки хочу вынести отключение проверки.

**Comment by BishopGIS** [comment]
Для отключения проверки сертификата необходимо в файле /home/user/.wxgis/wxGISCommon.xml
в тэге curl добавить атрибут ssl_verify="f"
например у меня это выглядит так:

``` xml
<curl proxy="" headers="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8|Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4|Accept-Encoding: gzip,deflate,sdch|User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36|Connection: keep-alive" dns_cache_timeout="180" connect_timeout="30" timeout="1000" ssl_verify="f"/>
```

**Comment by drnextgis** [comment]
А в GUI это сложно добавить?

**Comment by BishopGIS** [comment]
Там проблема не с добавлением в GUI а в том что много настроек не вынесено в GUI и их надо как-то логические организовать: отдельные страницы в диалоге, отдельные настройки, отдельные блоки. Сейчас всего 3 страницы: General, GDAL Configuration, Miscellanious. А настройки все время добавляются. Поэтому я пока не спешу все это оформлять, что бы не переделывать потом.
