### ISSUE TITLE
Кнопка "Создать Контейнер" ничего не делает

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#5]
Кнопка ничего не делает.
Находится в окне "Экспорт с параметрами".
![image](https://f.cloud.github.com/assets/4630662/2064132/a3dc390a-8cc5-11e3-9df2-62d2cac2844e.png)
Неинформативное название. Не понятно что обозначает это название, потому что оно больше нигде не встречается.

**Comment by BishopGIS** [comment]
Кнопка работает, просто с задержкой - это от ОС зависит
