### ISSUE TITLE
Неверная дата сборки в сплешскрине

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#51]
Вчера собрал - показывалось 11 октября, сегодня обновил код и снова собрал - опять показывает 11 октября.

**Comment by simgislab** [comment]
подверждаю, но у меня все время 6 окт показывает

**Comment by BishopGIS** [comment]
Это дата полной сборки. Т.е если сделать make clean && make && sudo make install
Обычно при сборке для пакетов deb выполняется полная сборка. 
А тут вы как девелоперы пересобираете поэтому и дата не меняется.

**Comment by drnextgis** [comment]
А почему у меня в сплешскрине одна дата (1 ноября), а `Помощь` - `О программе` - 2 ноября? Эти даты берутся что-ли из разных мест.

**Comment by BishopGIS** [comment]
Это потому что в коде стоит диектива препроцессора - **YEAR** и **DATE**
Эти даты будут одинаковы везед в программе при полной сборке в релизе. 
Вы собираете/пересобираете сами, вот и получается, где-то файл не 
скомпилировался, т.к. в нем не было изменений, где-то скомпилировался. 
Вот если ощибка проявится при make clean - когда все компилируется с 
нуля, тогда - да.

Best regards,
     Dmitry

02.11.2014 09:24, Denis Rykov пишет:
