### ISSUE TITLE
Русские название при включенном английском

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#52]
![screenshot from 2014-10-12 12 46 37](https://cloud.githubusercontent.com/assets/866124/4605210/5af0fa36-51d3-11e4-8333-95f99ef6fb9d.png)

**Comment by BishopGIS** [comment]
Для исправления надо make && make install и удалить из /home/user/.wxgis/wxGISCatalog.xml

**Comment by drnextgis** [comment]
Эта ошибка исчезла, но если выбрать русский - то в этом меню будет присутствовать пара элементов на английском.

**Comment by BishopGIS** [comment]
Да, к ним еще нет переводов.
