### ISSUE TITLE
Content - Preview

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#53]
Если вкладку Content перетащить на место вкладки Preview (поменять их местами), то потом не получается нажать на Preview, чтобы она заработала - нужно нажать опять на Content.

**Comment by BishopGIS** [comment]
Да, действительно. А вот этот функционал с перетаскиванием - он нужен?

**Comment by drnextgis** [comment]
Да не особо, тогда вообще отключи возможность перетаскивания.
