### ISSUE TITLE
NGM не запускается

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#54]
Поменял в настройках язык на Чешский, больше NGM не запускается.

**Comment by drnextgis** [comment]
При выборе несуществующего языка надпись Applying new configuration перекрывает окно с сообщением об ошибке - невозможно ничего прочитать, если его не сдвинуть.

**Comment by drnextgis** [comment]
Откуда вообще взялись эти языки - зачем они в списке, если для них нет перевода?

**Comment by BishopGIS** [comment]
Перевод есть, твоя система не поддерживает эту локаль. Т.е. в ней нет шрифтов и т.п. Вот на винде в системе все локали есть.

**Comment by BishopGIS** [comment]
С сообщением исправил. Проверь.

**Comment by drnextgis** [comment]
Да, сейчас всё хорошо.
