### ISSUE TITLE
Не перерисовывается канвас

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#55]
1. Выбираем какой-нибудь шейп и нажимаем Preview;
2. Инструментом идентификации выбираем прямоугольником несколько объектов;
3. В списке объектов кликаем правой кнопкой на любом и выбираем Zoom;
4. Выбираем другой файл (например растровую картинку) - она не появляется в Preview;

**Comment by BishopGIS** [comment]
У меня не воспроизводится. Но там обнаружился другой косяк с завершением потока отрисовки, который мог потнециально приводиться к такому. Закомитил для него фикс. Посмотри может помогло.

**Comment by drnextgis** [comment]
К сожалению, не помогло.

**Comment by BishopGIS** [comment]
Тогда ждем подтвержения у кого еще воспроизводится.

**Comment by drnextgis** [comment]
А если я переключившись на растровую картинку (которая не появляется в Preview) пользуюсь инструментом идентификации (по пустой области), то получаю загрузку процессора в районе 100%.

**Comment by BishopGIS** [comment]
Это по мотивам #35. Идентификация по растрам совсем не сделана. Поэтому пока рано разбираться, что там не работает.

**Comment by simgislab** [comment]
У меня не воспроизводится. Может особый растр-вектор?

**Comment by drnextgis** [comment]
Проверил. Ошибки больше нет.
