### ISSUE TITLE
Окно Свойства автоматически скроллится

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#66]
Открываем `Свойства` любого файла (например shp). Прокручиваем содержимое в самый конец. И нажимаем, например, `Центр X`. Содержимое окна автоматически сдвигается. Можно отключить такой поведение?

**Comment by BishopGIS** [comment]
У меня такое воспроизводится. Если прокрутить в конец и щелкнуть на текст в первой колонке ничего не происходит, если во второй, то немного дергается, но не скролится никуда. Дерганье из-за того, что вместо текстового контрола там рисуется контрол редактирования (хоть и Read only. Возможно такое нельзя убрать - надо посмотреть.

**Comment by drnextgis** [comment]
Да, я это дёрганье и имел в виду.
