### ISSUE TITLE
Отправить по почте

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#74]
Я собрал ngm без поддержки email (отключил в cmake), но пункт `отправить по почте` почему-то всё-равно присутствует в меню.

**Comment by BishopGIS** [comment]
А он активный?

**Comment by BishopGIS** [comment]
Пункт и будет присутсвовать, а то на все вариации сборки конфигов не напасесешься. Сделал вывод сообщения, что опция не была скомпилирована.

**Comment by drnextgis** [comment]
А можно `отправить` с большой буквы написать - `Отправить`?
![2014-11-01 18 15 02](https://cloud.githubusercontent.com/assets/866124/4871624/bf7e2a8a-61c0-11e4-993c-fd90127d9833.png)

**Comment by BishopGIS** [comment]
А так пункт меню называется. Я могу написать так: Command '...' support was not build. Там идет подстановка названия. Причем не только для этой возможности.

**Comment by drnextgis** [comment]
Я про то, что все пункты меню начинаются с большой буквы, а этот нет.

**Comment by BishopGIS** [comment]
А, понял. Но тут из-за #81 надо подумать вообще как сделать. 
Что-то типа субменю Отправить:
Отправить -> по почте
Отправить -> в архив
