### ISSUE TITLE
Пустой пункт меню Файл - Создать

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#75]
![2014-10-30 09 17 25](https://cloud.githubusercontent.com/assets/866124/4838101/638d2732-5fe3-11e4-8b0d-f084576178d2.png)

Может стоит делать пункт `Создать` не активным, если на данном уровне нельзя ничего создавать?

**Comment by BishopGIS** [comment]
Это не пункт, а submenu. Там нельзя сделать ни заблокированным ни еще как-то. В ArcGIS такое же поведение. Могу добавить фейковый пункт меню (например, <none>) в это submenu, но зачем?

**Comment by BishopGIS** [comment]
На всякий случай, оставлю здесь скриншот как это в ArcGIS выглядит.
![agempty](https://cloud.githubusercontent.com/assets/1708122/4861825/dd363c6c-6106-11e4-8cfc-7914cce02cba.png)

**Comment by yellow-sky** [comment]
Ахаха! :)

31 октября 2014 г., 17:05 пользователь Dmitry Baryshnikov <
notifications@github.com> написал:

> На всякий случай, оставлю здесь скриншот как это в ArcGIS выглядит.
> [image: agempty]
> https://cloud.githubusercontent.com/assets/1708122/4861825/dd363c6c-6106-11e4-8cfc-7914cce02cba.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/nextgismanager/issues/75#issuecomment-61264414
> .

## 

Best regards,

Nikulin Eugeny
