### ISSUE TITLE
Удаление символьных ссылок

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgismanager#77]
Сейчас если симлинк указывает на каталог, то при удалении через ngm всё содержимое каталога удаляется, а сама ссылка остаётся. Если же симлинк указывает на файл, то он не удаляется.

**Comment by BishopGIS** [comment]
А как надо?

**Comment by drnextgis** [comment]
1. Если симлинк ссылается на каталог, то удалять не сам каталог, а только симлинк;
2. Если симлинк ссылается на файл, то удалять симлинк, а не файл;
