### ISSUE TITLE
Ошибка при импорте SHP-файла в NGW 

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgismanager#78]
Fedora 20 x86_64,
NextGIS Manager (x86) Oct 29 2014, 
GDAL 2.0.0dev, released 2014/04/16
GTK3

При импорте файла вываливается окно:

Предупреждение: Rename field 'id' to 'id01'
Ошибка: Delete file failed! File '/tmp/wxgis/ngw2587822720_2.shp'
Ошибка: Delete file failed! File '/tmp/wxgis/ngw2587822720_2.shx'
Ошибка: Delete file failed! File '/tmp/wxgis/ngw2587822720_2.dbf'
Ошибка: Delete file failed! File '/tmp/wxgis/ngw2587822720_2.prj'
Ошибка: Библиотеке OGR не удалось открыть файл (Error code 400)

Слой при этом не создается.

**Comment by BishopGIS** [comment]
А этот же файл через веб интерфейс грузится? Просто похоже это ошибка НГВ, а не НГМ.

**Comment by yellow-sky** [comment]
Да, загрузился

30 октября 2014 г., 14:53 пользователь Dmitry Baryshnikov <
notifications@github.com> написал:

> А этот же файл через веб интерфейс грузится? Просто похоже это ошибка НГВ,
> а не НГМ.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nextgis/nextgismanager/issues/78#issuecomment-61080251
> .

## 

Best regards,

Nikulin Eugeny

**Comment by yellow-sky** [comment]
Забыл заметить, в файле не было ни одной записи

30 октября 2014 г., 14:57 пользователь Evgeny Nikulin nikulin.e@gmail.com
написал:

> Да, загрузился
> 
> 30 октября 2014 г., 14:53 пользователь Dmitry Baryshnikov <
> notifications@github.com> написал:
> 
> > А этот же файл через веб интерфейс грузится? Просто похоже это ошибка
> > НГВ, а не НГМ.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/nextgis/nextgismanager/issues/78#issuecomment-61080251
> > .
> 
> ## 
> 
> Best regards,
> 
> Nikulin Eugeny

## 

Best regards,

Nikulin Eugeny
