### ISSUE TITLE
Название вкладки "Список" неинформативно

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgismanager#8]
Название вкладки "Список" неинформативно. Я постоянно думаю, что это список записей в файле, а не список файлов в папке. 
![image](https://f.cloud.github.com/assets/4630662/2074000/7ddfc39e-8d6e-11e3-8e5b-fde7849a31da.png)
Предлагаю либо
- Переименовать его в "Список наборов данных", или
- Скрывать эту вкладку при просмотре содержимого шейпа или таблицы.

**Comment by BishopGIS** [comment]
Может быть назвать "Содержимое"? Ведь например в kml/kmz могут быть внутренние слои, но это же файл.

Есть предложения как еще более удобно сделать навигацию. Проблема в том, что проводник в Windows, показывает только папки, и там все просто, но у меня и папки и фалый показаны в дереве.
Это сделано для того, что бы удобно было перемещаться между файлами в режиме просмотра.
Может быть есть примеры более удобной навигации - во всяких AceDc, xnView и т.д. сделано примерно также.

**Comment by BishopGIS** [comment]
Назвал содержимое. Кстати это меняется в конфиге (wxGISCatalog.xml). Т.е. ничего компилировать не нужно.
