### ISSUE TITLE
В окне About неверное отображение архитектуры

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgismanager#89]
У меня всегда пишет x86, хотя собирал на 64битах

**Comment by drnextgis** [comment]
Подтверждаю.

**Comment by drnextgis** [comment]
Теперь работает.
![2014-10-30 18 26 52](https://cloud.githubusercontent.com/assets/866124/4843271/0aa8e5d2-6030-11e4-9819-144f2e7df991.png)

**Comment by yellow-sky** [comment]
Предлагаю писать x86_64 - общепринятое название 64х битной архитектуры
https://ru.wikipedia.org/wiki/X86-64
