### ISSUE TITLE
'To apply some changes' message

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgismanager#91]
To apply some changes the application... what?... needs to be restarted?

![](http://m-d.me/img/ss/2014-11-02-19-17-12.png)

**Comment by BishopGIS** [comment]
Just resize the dialog to see the full message,

**Comment by simgislab** [comment]
I tried by resizing down, it didn't help, resizing right helps.

I guess the line of text should break to new line if it can't fit.
